version: '3.8'
services:
    # Database Server
    # database: // name of the host
    localhost:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE='${DB_DATABASE}'
            - MYSQL_USER='${DB_USERNAME}'
            - MYSQL_PASSWORD='${DB_PASSWORD}'
            - MYSQL_ROOT_PASSWORD='${DB_PASSWORD}'
        # where we want to store our databases data
        volumes:
            # default location for storing mysql data
            - db-data:/var/lib/mysql

volumes:
    db-data: ~
